version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: 'games_backend_app:dev'
    working_dir: /app/src
    ports:
      - "8080:8080" 
    volumes:
      - ./src:/app/src
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    command: tail -f /dev/null

volumes:
  go-mod-cache:
  go-build-cache: